[[hftctp_lib]]
arch = "x86_64"
git-tree-sha1 = "e15024830a05daeae3c7a24b4e6c0c7ae0d50504"
os = "windows"

    [[hftctp_lib.download]]
    sha256 = "b3598610c279ba96c7eed0b81f531b45bf7b2ff45999c37573b525b4c260c3d9"
    url = "https://github.com/linanisyugioh/HFTCTP.jl/releases/download/V1.3.4/hftctp_windows_x64.tar.gz"
[[hftctp_lib]]
arch = "x86_64"
git-tree-sha1 = "f8a80d5228d6d534c16d4c60a21dd780bd3e8f8d"
libc = "glibc"
os = "linux"

    [[hftctp_lib.download]]
    sha256 = "f4469755cd30703578b587bd0ce8fd19ee101d49c7a414354244a716b62aad3e"
    url = "https://github.com/linanisyugioh/HFTCTP.jl/releases/download/V1.3.4/hftctp_linux_x64.tar.gz"
