[[hftctp_lib]]
arch = "x86_64"
git-tree-sha1 = "11abf046e967ebe78a4078655a813ea1d6f23ae0"
os = "windows"

    [[hftctp_lib.download]]
    sha256 = "7c7b0d4c3199f9bdcfebe1bfcec6a834e98a6c7e3fa2bd72fa699c1cda108c7b"
    url = "https://github.com/linanisyugioh/HFTCTP.jl/releases/download/V1.3.9/hftctp_windows_x64.tar.gz"
[[hftctp_lib]]
arch = "x86_64"
git-tree-sha1 = "f042f49fe85d5f25747986765bfd61d09633f2d0"
libc = "glibc"
os = "linux"

    [[hftctp_lib.download]]
    sha256 = "fd2648b2ffd0a16769fda43b4e1f7132906eccfd634d8767dd727e3f836eb177"
    url = "https://github.com/linanisyugioh/HFTCTP.jl/releases/download/V1.3.9/hftctp_linux_x64.tar.gz"
